### ISSUE TITLE
database does not exists

### ISSUE THREAD

**Issue by stijnsanders** [Borvik/vscode-postgres#101]
I'm getting messages like this in the output view:

    database ""MyDatabaseName"" does not exist

Though I am connected and everything works as it's supposed to. Notice the doubled double quotes, is that part of the cause? The message repeats when switching between open SQL files.

**Comment by Borvik** [comment]
I'm assuming that the database name actually contains quotes?

The switching between open files seems to indicate something with the language server for doing validation/intellisense. Are intellisense options like functions, columns, and tables showing as you type?  Do you get EXPLAIN powered error indicators?

**Comment by stijnsanders** [comment]
No I did not enter the database with quotes. Intellisense appears to work fine. What do you mean by explain powered error indicators?

**Comment by Borvik** [comment]
As you are crafting a query error squiggles will show up that are powered by postgres' EXPLAIN command.

I've tried opening a few queries and switching back and forth, but am unable to replicate the issue.  Do you have some steps that I can use to replicate this with?

**Comment by stijnsanders** [comment]
Yes, I get red squiggles, no problem there.
I've uninstalled the extension, re-installed the extension, and get the messages again rightaway. I guess my connections are stored somewhere else.
I remember when using the extension first, I would set up a connection using the indicator on the status-bar bottom left. Perhaps I've entered something wrong there and it is also persisted somewhere.
I've had a look in my personal `.vscode` folder, but couldn't find where you store connections. Where is the file you store them in?

**Comment by Borvik** [comment]
I'm not entire certain where they are stored (file-wise).  They are stored in the ExtensionContext global state.

Though you can use the context menu on a connection and choose "Edit" to access the "file" for a connection (uses a virtual file system).
