### ISSUE TITLE
Not sure when query is started/ongoing/finished

### ISSUE THREAD

**Issue by bjg2** [Borvik/vscode-postgres#11]
When query start is triggered, there's no way to know which query is finished, which not, and which query has execution is in progress. Example: if you run one update query, you will not get any feedback on whether the query executed or not. Also, errors on execution are seen only in popup in down-right, and it is easy not to spot them.

I think these should be feedbacks as important as tables with return results, and presented as them (it should be as easy to spot them as tables, probably in the same element). Confusion is even bigger because, whatever was the last command (update/delete/error), last select result is shown (in picture below last command was update, but I see only feedback on last select, before that).

![image](https://user-images.githubusercontent.com/6639273/40169756-013060c2-59c7-11e8-8de0-c724be15bb06.png)

Also, it would be really cool if query results could be in real table, like in mssql plugin. It would be easier to select, copy, etc.

PS. Apart from these problems, this is currently this is by far best PSQL plugin for VS Code :) Keep up good job!

**Comment by Borvik** [comment]
I can see the benefits of putting the results of other query types in the results window as well.

As for the table - the MSSQL plugin uses a TextDocumentContentProvider, as does this - and the results are already output in an html table (see src/common/previewProvider.ts).

As for knowing when individual queries start/stop, that is a bit more tricky.  For now, there isn't really any query parsing going on, so multiple queries get sent to the postgres server in one command - individual progress isn't tracked.  Parsing is planned, so it may be possible once I've got that sorted out.

**Comment by cthurston** [comment]
It may also be nice to have some basic query metrics, like how long the query took to run on the server, how long the data transfer took, how long it took to parse and display results, etc...

**Comment by yegorsb** [comment]
I am not 100% how difficult or easy it would be to implement, this could at least report back what has been effected by using the RETURNING keyword:

UPDATE table
SET field = 'a value'
WHERE field = 'an old value'
RETURNING *;

I know currently this type of query doesn't return the values back by the plugin, but it may worth while to see if this is feasible to implement.  
(https://www.postgresql.org/docs/9.5/static/dml-returning.html)

**Comment by Borvik** [comment]
I've used the RETURNING for postgres in applications I've built, but not this plugin.

There isn't really a use case for it here.  Putting it here would involve finding update statements within the query string and updating them and only them.  Plus I _really_ don't want to programmatically change the query someone is attempting to run - better to just change the how/where the results are output.

**Comment by Borvik** [comment]
I've implemented the core of this (show all results in the results pane - mixed with the tables) in version 1.1.0.

I will create a new issue with just the timing details in it as future development

**Comment by jlmagee** [comment]
@Borvik The lack of support for RETURNING means users cannot develop statements using that clause. It is also frustrating because the _n_ rows affected result made me think it was not working and I lost a good bit of time researching.  Please reconsider.

**Comment by Borvik** [comment]
@jlmagee RETURNING already works, and has worked since 1.1.0.

**Comment by jlmagee** [comment]
@Borvik  This query does not display data in the results pane. It only displays "1 row deleted"
DELETE FROM script_manager_service.vm_ip_address_pool vmip where vmip.vm_ip_address_pool_id = ( SELECT xvmip.vm_ip_address_pool_id FROM "script_manager_service"."vm_ip_address_pool" xvmip where xvmip.data_center = 'SOMELOC' and xvmip.realm_type = 'PICKIT' order by xvmip.vm_ip_address_pool_id LIMIT 1 ) RETURNING *;  

POSTGRESQL version
1.1.6
VSCODE version
Version: 1.32.0-insider
Commit: 804373ac4d5c84e96c8086cee5b9be132df88837
Date: 2019-03-01T18:18:05.574Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.13-200.fc29.x86_64

**Comment by Borvik** [comment]
ok - probably DELETE got missed, but works for INSERT/UPDATE - please create a NEW issue then.
