### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by maslamhussaini** [Borvik/vscode-postgres#117]
- Issue Type: `Performance`
- Extension Name: `vscode-postgres`
- Extension Version: `1.1.6`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/essamamdani/ckolkman.vscode-postgres-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Borvik** [comment]
stale - "attached" file not attached - not enough details
