### ISSUE TITLE
Add linting with pg-query-parser?

### ISSUE THREAD

**Issue by maxhawkins** [Borvik/vscode-postgres#121]
https://github.com/zhm/pg-query-parser

This node package uses the actual Postgres query parser code to parse queries and return syntax errors.

Maybe we could add it to the extension to get fast linting without connection to a postgres server?

There's also a pure-node emscripten port.

**Comment by Borvik** [comment]
I have seen that project, and others.  The biggest issue I have with those is that it locks the query parsing to the version of the postgres query parse that happened to be used by that library.  Most of them all use https://github.com/lfittl/libpg_query which looks topped out at PG10.  PG is now at 12.

**Comment by maxhawkins** [comment]
That makes sense, thanks.

Closing this now.
