### ISSUE TITLE
Code completion not working: schema ""query-service"" does not exist

### ISSUE THREAD

**Issue by bjwise96** [Borvik/vscode-postgres#129]
Code completion (table/column) stopped working on a database.  I'm getting this error:
schema ""query-service"" does not exist

I have a schema called query-service and I can browse it in the explorer.   I tried querying to see if I had a strange schema with quotes in the name and I didn't see anything using 

SELECT schema_name FROM information_schema.schemata

Any idea?

**Comment by bjwise96** [comment]
I found the queries that are erroring out in https://github.com/Borvik/vscode-postgres/blob/master/src/language/server.ts

I think it doesn't like my schema having a - in the name.  I'm going to remove that.  

`SELECT
          tbl.schemaname,
          tbl.tablename,
          tbl.quoted_name,
          tbl.is_table,
          json_agg(a) as columns
        FROM
          (
            SELECT
              schemaname,
              tablename,
              (quote_ident(schemaname) || '.' || quote_ident(tablename)) as quoted_name,
              true as is_table
            FROM
              pg_tables
            WHERE
              schemaname not in ('information_schema', 'pg_catalog', 'pg_toast')
              AND schemaname not like 'pg_temp_%'
              AND schemaname not like 'pg_toast_temp_%'
              AND has_schema_privilege(quote_ident(schemaname), 'CREATE, USAGE') = true
              AND has_table_privilege(quote_ident(schemaname) || '.' || quote_ident(tablename), 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER') = true
            union all
            SELECT
              schemaname,
              viewname as tablename,
              (quote_ident(schemaname) || '.' || quote_ident(viewname)) as quoted_name,
              false as is_table
            FROM pg_views
            WHERE
              schemaname not in ('information_schema', 'pg_catalog', 'pg_toast')
              AND schemaname not like 'pg_temp_%'
              AND schemaname not like 'pg_toast_temp_%'
              AND has_schema_privilege(quote_ident(schemaname), 'CREATE, USAGE') = true
              AND has_table_privilege(quote_ident(schemaname) || '.' || quote_ident(viewname), 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER') = true
          ) as tbl
          LEFT JOIN (
            SELECT
              attrelid,
              attname,
              format_type(atttypid, atttypmod) as data_type,
              attnum,
              attisdropped
            FROM
              pg_attribute
          ) as a ON (
            a.attrelid = tbl.quoted_name::regclass
            AND a.attnum > 0
            AND NOT a.attisdropped
            AND has_column_privilege(tbl.quoted_name, a.attname, 'SELECT, INSERT, UPDATE, REFERENCES')
          )
        GROUP BY schemaname, tablename, quoted_name, is_table;`

**Comment by Borvik** [comment]
Hmm... #161 might be a "duplicate" of this (and #33) - possibly the same error different spots.  I will have update both in the next release so this may be fixed then.

**Comment by Borvik** [comment]
likely fixed in v1.1.15 published minutes ago
