### ISSUE TITLE
unable to add database connection 

### ISSUE THREAD

**Issue by wibrt** [Borvik/vscode-postgres#131]
Using VSCodium
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-09T10:44:46.342Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-0.bpo.4-amd64 snap
Extension version: 1.1.11

In short:
pgadmin/dbeaver/psql connections work,
but connections from vscode take a while from step 'use secure connection|standard connection',
and stop responding when entering a database name with the error:
"connection terminated unexpectedlly"

![image](https://user-images.githubusercontent.com/17875724/79225850-adbb1a00-7e5d-11ea-8365-644cc255e549.png)

**Comment by takos22** [comment]
I have the same kind of issue where after the "Use Secure Connection/Standard Connection" prompt it takes a while then when I enter the database name I have to wait for like 30s before this message appears in the window log:
![image](https://user-images.githubusercontent.com/59511469/95628247-ee4ac780-0a7d-11eb-88a0-8ffa4567653e.png)

But then when you enter a database name this happens:
![when you enter a database name](https://user-images.githubusercontent.com/59511469/95627894-47662b80-0a7d-11eb-95cb-0148c14ef2e6.png)

PostgreSQL extension: v1.1.11
Vscode:
Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Borvik** [comment]
stale - separate issues - VSCodium not supported

**Comment by hitesh-dholariya-alation** [comment]
Try running the below commands inside the server where postgres is running.
1. cd /usr/local/pgsql/data
2. Edit pg_hba.conf
    a. Change Ipv4 line to host  all   all   all   trust
3. cd /usr/local/pgsql/data
4. Edit postgres.conf
    a. Change listen_addresses = '*'
5. Restart postgres:
    a. su postgres
    b. pg_ctl restart -D /usr/local/pgsql/data
6. Any issues with postgres, see logs in /usr/local/pgsql/data/log
