### ISSUE TITLE
Setup connection in Theia: hitting enter makes popup disappear

### ISSUE THREAD

**Issue by michalc** [Borvik/vscode-postgres#140]
I'm seeing if I can get this working in Theia... I have managed to create a .vsix file, copied it into the plugins folder, and it seems to load up ok.

However, I get the "Add database connection (1/7)" appearing, but adding a hostname and hitting enter makes it then disappear without going to (2/7).

<img width="1000" alt="Screenshot 2020-06-18 at 18 24 44" src="https://user-images.githubusercontent.com/13877/85052546-02964c00-b191-11ea-8083-73d10366cf8e.png">

Nothing seems relevant in the browser console, or in Docker standard output.

(Note also: I would love to have the connection details taken from an environment variable, or even a file, but not seen if that's possible)

**Comment by sivaraam** [comment]
I also observed this with Theia. It's hard to figure out why the extension is failing to establish a connection. It would be nice if this is fixed. Let m know if more information is needed to debug this.

**Comment by bjornhansen** [comment]
I ran into this as well and posted an issue with Theia: https://github.com/eclipse-theia/theia/issues/8777

Would be great to have the connection info in a JSON or able to use environment variables.

**Comment by Borvik** [comment]
I don't use Theia, and don't support issues that the extension may have outside of the normal VSCode environment.
