### ISSUE TITLE
Option to not show query for Select Top 1000

### ISSUE THREAD

**Issue by JMS55** [Borvik/vscode-postgres#141]
It would be nice to have an option to not open an editor with the query, when right clicking a table and choosing `Select Top 1000`. I want only the Results view to open.

**Comment by mohmyo** [comment]
I was going to open an issue for the same exact thing, It's completely annoying to open an editor for basic command stuff.

The extension is really great to browser the DB and sees data/schema changes while your wok on the fly, but this editor issue is very annoying.

@Borvik anything we can do about this?

**Comment by Borvik** [comment]
Came up with a solution involving a select submenu with some options to "Run Select Top" - the run options just run the query and show the results, while the "Select Top" options will show the query like normal.  This is in v1.1.16

**Comment by mohmyo** [comment]
@Borvik Keep the great work up!
