### ISSUE TITLE
Need foreign table support

### ISSUE THREAD

**Issue by ooooo84** [Borvik/vscode-postgres#142]
Version: 1.1.11

GREAT plugin with EXCELLENT code completion!

But cannot see any foreign tables under schemas, does it have support plan?

**Comment by Borvik** [comment]
With some new queries I'm working on it _may_ be possible, but I've never used foreign tables.

Do you know of a sample that would illustrate your use-case?  I'm confident enough of getting the foreign table _name_, but I want to test getting the columns.

**Comment by ooooo84** [comment]
case:
there are some FDWs in my case, such as postgresql, mysql or oracle.
i put these tables from FDWs into schemas named by dbms name. such as [mysql] schema holds all fdw tables from mysql, etc.

there has only mysql schema in schema list, no tables under schema.

**Comment by Borvik** [comment]
Sorry, I didn't mean the use-case itself. I understand from the docs just what a foreign table is and can appreciate their usefulness.

I just haven't ever worked with them and don't know how to set one up for testing purposes, and didn't know if you had some sample SQL that would allow me to learn/setup/test foreign tables.

**Comment by Borvik** [comment]
Took a bit to try and setup a fdw for testing, but foreign table support is in v1.1.16
