### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated

### ISSUE THREAD

**Issue by mohmyo** [Borvik/vscode-postgres#147]
[Error - 9:14:49 PM] (node:11440) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by jasonrudolph** [comment]
I started seeing this issue recently as well. I wonder if it's related to the recent upgrade to [VS Code 1.49](https://code.visualstudio.com/updates/v1_49). That VS Code update includes an [upgrade to Electron 9](https://code.visualstudio.com/updates/v1_49#_electron-90-update), which uses a newer version of Node.js (12.14.1), and perhaps this is a new deprecation in that version of Node?

**Comment by mohmyo** [comment]
I'm getting this specifically under `PostgreSQL Service` at the output tab

**Comment by Borvik** [comment]
I just looked through the extension code and the only place I am using a `Buffer` is in the `configFileSystem` where I enable editing of the db connection via fake files.  And that spot is already using `Buffer.from()`.

I can only assume it is from a dependency (though which I am uncertain at this point).

**Comment by netsrotr** [comment]
Got the same, with small diff:
 `[Error - 08:45:24] (node:2872) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

VS Code version: Code 1.49.0 (e790b931385d72cf5669fcefc51cdf65990efa5d, 2020-09-10T13:22:08.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-footnotes|bie|0.0.7
vscode-postgres|cko|1.1.11
FreeMarker|dco|0.0.9
svn-scm|joh|2.12.4
vscode-docker|ms-|1.6.0
csharp|ms-|1.23.2
mssql|ms-|1.9.0
remote-wsl|ms-|0.44.5
fluent-syntax-highlighting|pau|0.0.1
java|red|0.67.0
svn-scm-ext|spm|1.2.1
latex-support|tor|3.2.0
vscodeintellicode|Vis|1.2.10
vscode-java-debug|vsc|0.28.0
vscode-java-dependency|vsc|0.13.0
vscode-java-pack|vsc|0.10.0
vscode-java-test|vsc|0.24.2
vscode-maven|vsc|0.24.2
markdown-all-in-one|yzh|3.3.0

</details>

**Comment by piotr277** [comment]
The same for me :(
`(node:8931) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`
VS Code v. 1.49.1, tested on osx and linux

**Comment by janishorsts** [comment]
Maybe one of these dependencies? I downloaded vscode-postgres, run `npm i` and found all potential modules that use deprecated Buffer constructor - I don't know which ones are actually run in nodejs by vscode-postgres.

`~ grep "new Buffer" $(grep "('buffer')" -R * | cut -d: -f1) | cut -d: -f1 | sort | uniq
node_modules/asn1.js/lib/asn1/base/buffer.js
node_modules/asn1.js/lib/asn1/decoders/pem.js
node_modules/asn1.js/lib/asn1/encoders/der.js
node_modules/buffer-crc32/index.js
node_modules/clone-buffer/index.js
node_modules/des.js/test/cbc-test.js
node_modules/des.js/test/des-test.js
node_modules/des.js/test/ede-test.js
node_modules/gulp-gunzip/node_modules/readable-stream/lib/_stream_readable.js
node_modules/gulp-gunzip/node_modules/readable-stream/lib/_stream_writable.js
node_modules/gulp-gunzip/node_modules/string_decoder/index.js
node_modules/gulp-untar/node_modules/vinyl/lib/cloneBuffer.js
node_modules/mocha/mocha.js
node_modules/ripemd160/index.js
node_modules/safe-buffer/README.md
node_modules/stream-http/test/browser/auth.js
node_modules/stream-http/test/browser/binary-streaming.js
node_modules/stream-http/test/browser/cookie.js
node_modules/stream-http/test/browser/text-streaming.js
node_modules/to-arraybuffer/test.js
node_modules/vinyl/lib/cloneBuffer.js`

For example, vinyl uses deprecated Buffer

`~ cat node_modules/vinyl/lib/cloneBuffer.js 
var Buffer = require('buffer').Buffer;

module.exports = function(buf) {
  var out = new Buffer(buf.length);
  buf.copy(out);
  return out;
};`

**Comment by gdvallance** [comment]
I am getting the error too. Running VS Code 1.49 / Electron 9.2.1 etc. on Windows 10 / 64bit.

**Comment by mianyuwang** [comment]
> Maybe one of these dependencies? I downloaded vscode-postgres, run `npm i` and found all potential modules that use deprecated Buffer constructor - I don't know which ones are actually run in nodejs by vscode-postgres.
> 
> ```shell
> ~ grep "new Buffer" $(grep "('buffer')" -R * | cut -d: -f1) | cut -d: -f1 | sort | uniq
> node_modules/asn1.js/lib/asn1/base/buffer.js
> node_modules/asn1.js/lib/asn1/decoders/pem.js
> node_modules/asn1.js/lib/asn1/encoders/der.js
> node_modules/buffer-crc32/index.js
> node_modules/clone-buffer/index.js
> node_modules/des.js/test/cbc-test.js
> node_modules/des.js/test/des-test.js
> node_modules/des.js/test/ede-test.js
> node_modules/gulp-gunzip/node_modules/readable-stream/lib/_stream_readable.js
> node_modules/gulp-gunzip/node_modules/readable-stream/lib/_stream_writable.js
> node_modules/gulp-gunzip/node_modules/string_decoder/index.js
> node_modules/gulp-untar/node_modules/vinyl/lib/cloneBuffer.js
> node_modules/mocha/mocha.js
> node_modules/ripemd160/index.js
> node_modules/safe-buffer/README.md
> node_modules/stream-http/test/browser/auth.js
> node_modules/stream-http/test/browser/binary-streaming.js
> node_modules/stream-http/test/browser/cookie.js
> node_modules/stream-http/test/browser/text-streaming.js
> node_modules/to-arraybuffer/test.js
> node_modules/vinyl/lib/cloneBuffer.js
> ```
> 
> For example, vinyl uses deprecated Buffer
> 
> ```shell
> ~ cat node_modules/vinyl/lib/cloneBuffer.js 
> var Buffer = require('buffer').Buffer;
> 
> module.exports = function(buf) {
>   var out = new Buffer(buf.length);
>   buf.copy(out);
>   return out;
> };
> ```

what does `npm outdated` show to you, maybe this project needs a tune-up to pick up the latest dependencies.

**Comment by basharatusman** [comment]
Getting the same error as well after installing the plugin.

`[Error - 7:56:24 PM] (node:20424) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

VSCode - 1.49.1

**Comment by gdvallance** [comment]
@Borvik Is there a timeline for fixing this warning? I would like to help but I am not a developer in this space -- just a user of VS Code and Postgres ... That said, is there anything I can do to help given my limitations?

**Comment by guidopontet** [comment]
Same here. VSCode specs:

```
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:33.049Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.15.0-118-generic
```
The message under Output tab, on `PostgreSQL Service` is:

```
[Error - 9:07:29 AM] (node:8531) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by Borvik** [comment]
I have seen and replicate the error - the problem is an underlying dependency (or dependency of a dependency) is causing the error.  In my test scenario, I upgraded everything I could to the latest versions and _still_ saw this deprecation warning.

**Comment by alisabzevari** [comment]
I think I have managed to find the guilty package by adding the following code in `extensions.ts` and debug the project. I found the solution [here](https://stackoverflow.com/a/50432372/692422).

```js
process.on('warning', (warning) => {
    console.log(warning.stack);
});
```
I have created a fix PR. Please have a look @Borvik.

**Comment by Borvik** [comment]
@alisabzevari - got to reopen this - thought it would fix it, but it didn't.

**Comment by Borvik** [comment]
Thanks to @alisabzevari `process.on` suggestion - I may finally have a lead on this:

```
[Error - 9:17:21 AM] (node:14736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:174:11)
    at Buffer (buffer.js:257:3)
    at new <anonymous> (c:\Users\ckolk\Desktop\Projects\vscode-postgres\node_modules\buffer-writer\index.js:6:17)
    at new Connection (c:\Users\ckolk\Desktop\Projects\vscode-postgres\node_modules\pg\lib\connection.js:30:17)
    at new Client (c:\Users\ckolk\Desktop\Projects\vscode-postgres\node_modules\pg\lib\client.js:40:37)
    at new PgClient (c:\Users\ckolk\Desktop\Projects\vscode-postgres\out\language\server.js:25:9)
    at c:\Users\ckolk\Desktop\Projects\vscode-postgres\out\language\server.js:97:28
    at Generator.next (<anonymous>)
    at c:\Users\ckolk\Desktop\Projects\vscode-postgres\out\language\server.js:8:71
    at new Promise (<anonymous>)
```

working towards a resolution

**Comment by alisabzevari** [comment]
I also found out that I get the error when I have live-share extension pack enabled. I am trying to figure out why it happens.
