### ISSUE TITLE
This extension for visual studio

### ISSUE THREAD

**Issue by genny-s** [Borvik/vscode-postgres#148]
Hello!
I use visual studio and this extension is interesting to me as we use postgreSQL.
Is it possible to port this extension to a visual studio?

**Comment by Borvik** [comment]
The question was a bit ambiguous, so I will answer the 3 interpretations of it that I see.

1. Is it possible? Of course it's possible
2. Is it possible for _me_ to port the extension? Technically possible I do have C# experience, but no VS extension experience so it would take quite a bit.
3. Will I port this extension? Probably not, I barely have time to maintain this one let alone a port of it.
