### ISSUE TITLE
"self signed certificate" error

### ISSUE THREAD

**Issue by abiatarprado** [Borvik/vscode-postgres#154]
Hello. What can the "self signed certificate" error mean when I try to add a heroku database?

**Comment by marcdepoe** [comment]
I too am having SSL issues in version 1.1.13 whenever I try to connect to any database:
**Error unable to verify the first certificate**
I reverted to version 1.1.11 and everything works fine.

**Comment by Borvik** [comment]
Likely has something to do with the upgrade of the `pg` library to fix issue #147 

I will look into it when I get a chance

**Comment by chartpath** [comment]
<img width="499" alt="Screen Shot 2020-10-21 at 2 42 49 PM" src="https://user-images.githubusercontent.com/461274/96768285-b449c180-13ab-11eb-8801-460126a97190.png">

Not sure if that was the issue since I also downgraded to 1.11 and am still getting this.

**Comment by Borvik** [comment]
This should be solved in `1.1.14` - indeed it was the upgrade of `pg`
