### ISSUE TITLE
Unable to recognize letter case in column name. 

### ISSUE THREAD

**Issue by olivier-tgrisk** [Borvik/vscode-postgres#158]
Query language does not recognize letter case when running a query. Not sure if that is expected behavior.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/66389440/102001642-b61d6a80-3cf4-11eb-973a-c75abb86c32d.png">

**Comment by Borvik** [comment]
The error is coming from your Postgres server itself.  Postgres actually both, does and doesn't care about case-sensitivity in table/column identifiers.

It does in that if you create a table/column with upper-case, you need to reference it as upper-case.

It doesn't in that by default if you just use upper _or_ lower case in your SQL statements, it _normally_  just transforms them to lower case.  In which case all would map to lower.

In _your_ case, it looks like your column may have been created as upper-case, so you need to reference it in upper case.  You can do so by the following: `WHERE f_swat_control."CAPABILITY" = true`.  Double-quotes in postgres indicate that what is inside is an `identifier` and must be used verbatim - which means it can have special character (including spaces).  It also means use the case verbatim as well.

Again - this is a function of Postgres, and not this plugin.
