### ISSUE TITLE
Incorrect error when using ALTER

### ISSUE THREAD

**Issue by vBread** [Borvik/vscode-postgres#160]
When writing an `ALTER TABLE` query, an error incorrectly displays.

![Screen Shot 2021-01-04 at 2 55 08 PM](https://user-images.githubusercontent.com/60681223/103573895-03789c00-4e9d-11eb-91af-b3db0697e18b.png)

However, when executing the query, it does go through.

**Comment by Borvik** [comment]
Right... in some cases this is expected

> It is possible there are some queries that won't run and report problems - even if they are completely valid (`DROP DATABASE` comes to mind).

This is because `EXPLAIN ANALYZE ALTER TABLE users RENAME card_id TO card;` actually does return that error from the PostgreSQL server.

At this point, there isn't much that can be done about this.

**Comment by arenick001** [comment]
`alter table public.room_members enable row level security;`
also shows `syntax error at or near "alter"`.but `EXPLAIN ANALYZE alter table public.room_members enable row level security;` does not return error.
how can i solve this?
