### ISSUE TITLE
Save result to JSON, CSV, XML not working correctly

### ISSUE THREAD

**Issue by debegr92** [Borvik/vscode-postgres#164]
I have a simple query with a JOIN statement. My result shows three columns correctly, but if I try to export the result, not all data is shown correctly.
One column of the result has some **empty text**. Maybe this is the problem here?

**Comment by debegr92** [comment]
Checked this one again...
For XML and JSON, only the **last** column is exported. With CSV only the **first** one will be exported.

I tried all this without the empty text column in the result, so this is not the problem.

For me the export is not working with a JOIN in the query :(

**Comment by Borvik** [comment]
I just tested with a simple join query and everything appears to be working fine - perhaps you can give more of a specific example.

![image](https://user-images.githubusercontent.com/1764750/105702083-3c72c200-5ed9-11eb-875f-92c9d10ae7c3.png)

Also tried emptying a column - still worked fine
![image](https://user-images.githubusercontent.com/1764750/105702333-a9865780-5ed9-11eb-91ee-39c2f667cb05.png)

**Comment by debegr92** [comment]
Yes! I found out, that the column names has to be unique (for sure).
**Maybe a popup dialog would be helpful?**
I have the same column name in the joined table. With a new name using AS, everything is working.

![grafik](https://user-images.githubusercontent.com/4254744/105765987-78e60280-5f59-11eb-828a-2ade3c24f40d.png)

![grafik](https://user-images.githubusercontent.com/4254744/105765939-69ff5000-5f59-11eb-8f7d-84fbb1c75dfd.png)

**Comment by Borvik** [comment]
Actually...  this did reveal an issue.

There is some code in place that _is_ supposed to prevent this by detecting columns with the same name and adding a number after duplicates so your example _should_ have done something like this for `json` and `xml`:

```
{
  "name": "Monzelfeld",
  "name_1": "Rheinland-Pfalz"
}
```

CSV is handled a little differently so not sure yet what can be done there, but this can be solved.
