### ISSUE TITLE
Support pl/pgsql

### ISSUE THREAD

**Issue by yassun4dev** [Borvik/vscode-postgres#167]
IDE linter does not support pl/pgsql.

I get a warning when editing a Stored procedure/function.

It is difficult to support pl/pgsql?

**Comment by Borvik** [comment]
Yes, it would be _very_ difficult to support pl/pgsql - the error checker essentially just runs an `EXPLAIN ANALYZE` on the statement and highlights the returned error.

**Comment by yassun4dev** [comment]
Thank you for answering.
