### ISSUE TITLE
not able to connect AWS RDS for postgresql

### ISSUE THREAD

**Issue by matsujju** [Borvik/vscode-postgres#168]
I am getting error while trying to connect AWS postgresql database.

`connect ETIMEDOUT 65.2.133.208:5432`

**Comment by Borvik** [comment]
AWS RedShift is _based_ on postgresql - but prevents queries necessary for gathering metadata and is thus not supported.

**Comment by matsujju** [comment]
so how do you suggest i should proceed for connecting AWS database in vscode?

**Comment by cdvv7788** [comment]
`AWS RedShift` != `AWS Relational Database Service`. RDS is basically a managed postgres service. No idea about redshift (data warehouse service).

**Comment by matsujju** [comment]
@cdvv7788 @Borvik can we create postgresql database on AWS for free and connect through this extension in vscode for access and querying? any articles you can suggest if possible? I am new to database services offering in market.

**Comment by Borvik** [comment]
Really?  They've got so many services, it's hard to keep straight 😄. I didn't even know about that one.  I don't know the capabilities of the RDS, but my guess is it's probably similarly hobbled - I also personally don't use AWS, so I have no way to test (unless they have a free tier - but really with all the compatible db services I don't have time to test on all of them).

**Comment by cdvv7788** [comment]
@matsujju I would suggest starting by connecting using the postgresql-client `psql`. If you cannot connect that way, you may need to open the permissions for the database to be accessed from your IP.
