### ISSUE TITLE
Result Views Empty

### ISSUE THREAD

**Issue by jrussellsmyth** [Borvik/vscode-postgres#172]
With the latest version of VSCode, result views are blank. Verified related to version by downloading April 2021 from https://code.visualstudio.com/updates/v1_56 and views work again.

ckolkman.vscode-postgres v 1.1.17

VSCode
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z (2 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 18.7.0

**Comment by Borvik** [comment]
This should be solved in v1.1.18
