### ISSUE TITLE
Copy to clipboard from query results does not work

### ISSUE THREAD

**Issue by jiri-matejka** [Borvik/vscode-postgres#176]
Copy to clipboard from query results, regardless of doing by Ctrl+C or context menu, does nothing.

VSCode: 1.58.2
VsCode-Postgres: 1.1.18
Ubuntu 20

**Comment by Borvik** [comment]
I happen to normally run Ubuntu and am using the same vscode and extension version.

I just tried, and I am unable to replicate this.

**Comment by jiri-matejka** [comment]
After extension reinstall and VSCode restart, the Ctrl+C works for me, but context menu command Copy does not..

**Comment by Borvik** [comment]
I can confirm the issue - however, the context menu is not something I built, but was rather built-in to the WebView - which is being used to show the results.  The issue is in VSCode itself.

**Comment by Kampfmoehre** [comment]
Sorry to comment on old issue, but I am experiencing the same problem for a long time now. Could this happen to be related to this problem?
https://stackoverflow.com/questions/70788421/context-menu-copy-is-not-working-in-vscode-webview-but-ctrlc-is-working-fine
