### ISSUE TITLE
HOW IN THE WORLD DO YOU RUN QUERY????

### ISSUE THREAD

**Issue by damircolak** [Borvik/vscode-postgres#179]
I installed the extension I connected to the server and database, I opened a new file test.sql, I wrote select * from tablename and.... HOW TO RUN THE QUERY????????

There is no toolbar button, F5 is saying "don't know how to debug SQL file extension"

HOW DO YOU RUN A QUERY??????

**Comment by Borvik** [comment]
Language mode must be PostgreSQL, and you must have a sever/db showing in the status bar
