### ISSUE TITLE
unable to connect using settings that work for psql

### ISSUE THREAD

**Issue by judell** [Borvik/vscode-postgres#189]
I am using https://steampipe.io which embeds a Postgres instance. I can connect (from WSL2) like so:

`psql -U steampipe -d steampipe -h localhost -p 9193`

The same settings in the extension (installed remote/WSL) result in:

`no pg_hba.conf entry for host "127.0.0.1", user "steampipe", database "postgres", SSL off`

settings:

```
{
  "label": "local steampipe",
  "host": "localhost",
  "user": "steampipe",
  "port": 9193,
  "ssl": false,
  "database": "steampipe",
  "password": "9a49-42e2-a57e"
}
```

Could be a networking issue, I'm running VSCode itself in Windows, but would expect the extension running in WSL to behave the same as `psql -U steampipe -d steampipe -h localhost -p 9193` in a WSL terminal?

https://github.com/Borvik/vscode-postgres/issues/32 possibly related?

**Comment by Borvik** [comment]
While I can't explain it, I do not think it is an issue with this extension itself.

The values in the settings (as entered in Add Connection) - are passed directly to the underlying library that handles the connection.

A true test might be to try a nodejs program within the WSL and see if it can connect to steampipe using the `pg` library (https://node-postgres.com/features/connecting - I did _not_ use pools, and I programmatically pass the connection information to a `new Client` vs using env variables).
