### ISSUE TITLE
SSL connection gives no pg_hba.conf entry SSL off error

### ISSUE THREAD

**Issue by zszabo14** [Borvik/vscode-postgres#190]
HI

I'm trying to connect to an SSL secured server:

```
{
  "label": "CDA",
  "host": "xxxxxxxxxxxxxxxxxxxxx",
  "user": "admin",
  "port": 32657,
  "ssl": true,
  "database": "",
  "password": "password"
}
```

and got:

`ERROR: no pg_hba.conf entry for host "xxx.xxx.xxx.xxx", user "admin", database "mydababase", SSL off`

I couldn't find how the SSL cert apply.

**Comment by Borvik** [comment]
see: #54

**Comment by zszabo14** [comment]
When a user clicks on the + sign and add a new connection and select Use Secure Connection, you are not asking for this parameter. (or use a cert manager service) 
Also don't store the password as plain text.

**Comment by NewAlexandria** [comment]
The solution in #54 doesn't work for me.  Can you please reiterate it with a bit more detail?   I'm wondering if anything changed in the past 7 months, with heroku connections

**Comment by Borvik** [comment]
nothing has changed, and I tested it still works for heroku.  you must EDIT the connection to add a `certPath` to the configuration in order to get SSL to work
