### ISSUE TITLE
Input is not valid base64-encoded data.

### ISSUE THREAD

**Issue by AhmedKamal20** [Borvik/vscode-postgres#196]
Every time now when I try to `Select Postgres Server` I get this error
I installed the extension lately and added 3 connections, and it worked fine for a while
But now when I try to init new query or open the Postgres Explorer
I get this error (the logs form the console):
 
```
notificationsAlerts.ts:42 Input is not valid base64-encoded data.
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:569
fire @ event.ts:736
addNotification @ notifications.ts:206
error @ notificationService.ts:92
executeCommand @ statusbarItem.ts:194
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
(anonymous) @ statusbarItem.ts:127
```

Any Idea Why?

**Comment by Borvik** [comment]
It has something to do with the newest version of VSCode.  Reverting seems to work for now.

**Comment by Nipuns1999** [comment]
I'm getting the same error as well. My vscode version is 1.66.2. Is there any workaround to get this resolved?

**Comment by Borvik** [comment]
Did you maybe mean `1.66.2`?  I haven't seen this issue with older versions of vscode.

Are you by chance using vscode on linux installed via snap?

Apparently they changed secret storage in 1.66.1 and that is when this broke.  Rolling back vscode to 1.66.0 has worked to keep this extension running

**Comment by AhmedKamal20** [comment]
@Borvik As I Understand from the VS Code issue, if we can reset the secret storage and add the connections again , it will work fine 
Do you know who to reset the secret storage for this extension only ?     
because i tried to add new connection and it doesn't work, i guess i need to clean the storage first

**Comment by Borvik** [comment]
It kinda does sound like that, but no I don't have a concrete way to reset it.

Perhaps, if you go down to 1.66.0, then remove the connections - then upgrade back to 1.66.2, and add the connections - maybe it would work.

The connections themselves aren't stored in secret - just the passwords - and the secret storage is only accessed per connection, so in theory - maybe that will work.

**Comment by Nipuns1999** [comment]
I did rolled back to 1.64.2 but it did not work though. And yes using vscode on Linux and installed via snap. 
I tried to install 1.64.2 version through Debian package, but i still encountered the error though.

**Comment by Borvik** [comment]
this does appear to be working again in vscode 1.67.0

**Comment by AhmedKamal20** [comment]
> this does appear to be working again in vscode 1.67.0

Confirmed

**Comment by Borvik** [comment]
Possibly - though sidebar was working on my snap installed instance at work.

I noticed they _did_ reopen that issue - as the person meant to verify it still had the issue according to their test case - so perhaps it doesn't fix it for everyone?

They mentioned:
> Will need to investigate further but don't think this needs to be a candidate.

Maybe that means we wouldn't have to wait till 1.68, but maybe 1.67.1?

**Comment by AhmedKamal20** [comment]
Yeah, probably.
Thank you very much for all your replies and help.

**Comment by Borvik** [comment]
and... back to not working for me either (1.67.1)

**Comment by AhmedKamal20** [comment]
Yeah, it's gives me "Cannot get password"

**Comment by Borvik** [comment]
wow - looks like its taken a while, but MS looks like they finally have something for snap users.

looks like after a lot of trial and error with regard to their new secret encryption (which was kinda double-encrypted thanks to the keyrings) - it looks like they are gutting it only for snap users.

hopefully there will be an update soon that makes this work again.
