### ISSUE TITLE
PostgreSQL: Select Connection resulted in error (no pg_hba.conf entry for host)

### ISSUE THREAD

**Issue by jt356** [Borvik/vscode-postgres#204]
Type: <b>Bug</b>

VSCode will connect to the database, at startup, because its set up as "Vscode-postgres: Default Connection", and everything works fine.

But every time i try to connect to the same DB by Ctrl+Shift+P "PostgreSQL: Select Connection" i will get connected, but i will also get a popup window with following error:

Visual Studio Code

Command 'PostgreSQL: Select Connection' resulted in an error (no pg_hba.conf entry for host "123.456.789.0", user "myusername", database "postgres", SSL on)

Database name is not "postgres", as in error message.
Im using only one remote Postgresql database. 

My pg_hba.conf (located at c:\Program Files\PostgreSQL\14\data\ ) looks like this (i removed the commented lines):

```
local   all             all                                     scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256
local   replication     all                                     scram-sha-256
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256

# ADDED BY ME:
hostssl all all 0.0.0.0/0  trust
hostssl all all ::0/0  trust
```

Extension version: 1.4.0
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (7.05GB free)|
|Process Argv|--crash-reporter-id 9843a9bb-046d-441b-b649-060c344de8ad|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

<!-- generated by issue reporter --
<img width="707" alt="PostgreSQ Select Connection error" src="https://user-images.githubusercontent.com/100563710/185578873-c9dd47b3-c714-48d4-8d3a-5d686de7e3ac.png">
>

**Comment by Borvik** [comment]
The extension use the `postgres` database to gather metadata for intellisense - so it will attempt to connect to `postgres`, even if your connection is for a different database.  It will use your target database for running `EXPLAIN` queries for syntax checking.

The `pg_hba.conf` error is not one being generated by the extension, but rather the server that you are connecting to.

Looking at your conf file, I was not familiar with `0.0.0.0/0` or more specifically the `0` mask for allowing everything - though I'm not sure I would `trust` all ips everywhere.

But that made me consider the IPv6 version, I looked that up - the examples I've seen show `::/0` not `::0/0`.  To me the explanation for them makes them seem identical, but maybe they aren't.

Though this seems to be an issue with postgres - which is where the error is coming from, not the extension.
