### ISSUE TITLE
INT showing as error

### ISSUE THREAD

**Issue by rithle** [Borvik/vscode-postgres#208]
INT is underlined as an error in Postgres language file. Query still runs correctly and table created.

CREATE TABLE basket_a (
    a INT PRIMARY KEY,
    fruit_a VARCHAR(100) NOT NULL
);

**Comment by rithle** [comment]
Issue no longer occurring after vscode re-start. Closing issue.

**Comment by Borvik** [comment]
> It is possible there are some queries that won't run and report problems - even if they are completely valid (DROP DATABASE comes to mind).

While this one runs - it fails the `EXPLAIN ANALYZE` that powers the error checking.
