### ISSUE TITLE
Columns of type Date are displayed as one day off

### ISSUE THREAD

**Issue by fonata** [Borvik/vscode-postgres#219]
The output from the `psql` command line differs from the output in Visual Studio Code by one day.

CLI (everything as expected):  
![image](https://user-images.githubusercontent.com/6819464/231726747-09943db5-1302-4f27-a2bb-3587e9ea219f.png)

Within Code (date is shown strangely):  
![image](https://user-images.githubusercontent.com/6819464/231727137-195f979d-b43e-40ad-969d-20e89bfca55d.png)

Local time zone is UTC/GMT +2 h. Server time zone is UTC + 0 h. Current time is around noon, so time zones should not mess with me here. The competing extension SQLTools is not affected and shows the date correctly.

Operating system is Ubuntu 20.04
Extension version: v1.4.1
VS Code version: 1.77.1

**Comment by Borvik** [comment]
this does look like something to be investigated, though a quick test reveals that it is likely time zone related... just maybe not in the most obvious way.

I think it has something to do with how it is stored in postgres (no timestamp, no time zone) - and how the `pg` library converts that to a js `Date` object upon receiving it.  Can't confirm that just yet - but I can likely alter that if that's the case.

**Comment by Borvik** [comment]
This should be corrected in 1.4.3
