### ISSUE TITLE
Can't build current release

### ISSUE THREAD

**Issue by peterbam** [Borvik/vscode-postgres#22]
Seems like .vscode/launch.json has "program": "${workspaceFolder}/test.js", probably should be "program": "${workspaceFolder}/out/extension.js"?

When that changed, won't start as cant find 'vscode'? npm install reports all OK

Previous builds worked OK?

**Comment by Borvik** [comment]
Yes builds still actually work ok.  This isn't a "program" per se, and needs to be loaded specially.  See the "Extension" configuration in the launch file.

The test one you are referring to is left over from my tests, when I was testing a specific bit of isolated code.  It can be safely removed.

**Comment by peterbam** [comment]
Thanks, that fixed it
