### ISSUE TITLE
Intellisense not working.

### ISSUE THREAD

**Issue by iklein99** [Borvik/vscode-postgres#221]
I'm finding that I'm getting syntax errors showing up in pgsql files.

<img width="232" alt="Screenshot 2023-04-25 at 8 20 18 AM" src="https://user-images.githubusercontent.com/5103250/234274261-272df5c6-d0c7-42da-85b3-97c53438bc26.png">

**Comment by Borvik** [comment]
See this for an explanation: https://github.com/Borvik/vscode-postgres/issues/160
