### ISSUE TITLE
can't handle valid set syntax

### ISSUE THREAD

**Issue by dotysan** [Borvik/vscode-postgres#224]
Example:
```sql
set intervalstyle = 'sql_standard';
```

![image](https://github.com/Borvik/vscode-postgres/assets/5060170/7b2727fa-fff9-421b-ac93-323f68686804)

AFAIK, that's perfectly valid PostgreSQL.

**Comment by Borvik** [comment]
See this for an explanation: https://github.com/Borvik/vscode-postgres/issues/160

**Comment by dotysan** [comment]
Aha, I see it in the db console now. Thanks for explanation.
```
db-1   | 2023-05-19 16:46:27.117 UTC [462] ERROR:  syntax error at or near "set" at character 9
db-1   | 2023-05-19 16:46:27.117 UTC [462] STATEMENT:  EXPLAIN set intervalstyle = 'iso_8601';
```

**Comment by Borvik** [comment]
as for hiding the output... I would not propose that entirely... mainly because with 0 output you wouldn't know success/failure of the command being run

however changing the format/output for various commands (like SET, or other non-standard results) would definitely be considered

**Comment by dotysan** [comment]
Agreed. Maybe just `[command] success` or something similar.

**Comment by dotysan** [comment]
Which brings me to my original issue, how to override the format for an interval?

It appears to be hard-coded to iso_8601, but I'd like to change it to `sql_standard`. But doing anything with `intervalstyle` seems to produce corrupt output.

**Comment by Borvik** [comment]
in order for the interval to be formatted and parsed by the extension - it needs to be returned from postgres in a consistent format

to alter the format uses a setting:
![image](https://github.com/Borvik/vscode-postgres/assets/1764750/eabcf7fe-06eb-45e9-9524-358b833d4e3e)

**Comment by dotysan** [comment]
Yep, thx! Just found that. Sorry for the noise.
