### ISSUE TITLE
Confirming this extension works without a PG client install? And curious how?

### ISSUE THREAD

**Issue by mmdolbow** [Borvik/vscode-postgres#228]
I just started using this extension and really like it. Because VS Code is pretty easy for my colleagues to acquire/install, and extensions are useful, I'd like to use it for some general "intro to SQL" training. But here's one thing I don't understand: it works *without* a PG client installation on Windows. (I can currently connect to an Azure PostgreSQL DB and run queries with the extension, but I don't have a client install.) At least, that's how it appears to me when I use it - I don't remember installing a client, I don't see any PG files under C:\Program Files, and of course the extension doesn't mention it as a prerequisite.

I'll probably need to do a client ODBC install at some point so I can do other connections, like with PowerShell, but I'm curious if this same behavior will apply to my colleagues, who likely *won't* be able to do a client install without help.

**Comment by Borvik** [comment]
no, it doesn't need a separate pg client install.  It uses the node package `pg` internally which handles the connections.

**Comment by mmdolbow** [comment]
That is terrific, thanks for answering!
