### ISSUE TITLE
can not find postgres in list

### ISSUE THREAD

**Issue by MahyarFardin** [Borvik/vscode-postgres#235]
Hi, I cannot choose my connection and it does not allow me to pass this step. Also, I have Postgres service enabled and it is running on my pc.
![image](https://github.com/Borvik/vscode-postgres/assets/95848199/afe843c1-f6cc-479d-8828-a847c32fbb5b)

**Comment by MahyarFardin** [comment]
added

**Comment by Borvik** [comment]
from your screenshot:
![image](https://github.com/Borvik/vscode-postgres/assets/1764750/86f2a525-ec41-4980-9a6f-3d07446e8e8a)

**Comment by MahyarFardin** [comment]
> from your screenshot: ![image](https://user-images.githubusercontent.com/1764750/262642783-86f2a525-ec41-4980-9a6f-3d07446e8e8a.png)

I tried everything but nothing seems to work including 'root' and etc.

**Comment by Borvik** [comment]
Ultimately this is not going to be an extension issue.

Basically it's saying that your username/password that you are supposed to use when setting up the connection is incorrect.

Either that or your postgres server isn't configured properly to accept username/password over TCP - which is usually setup in the `pg_hba.conf` file.

**Comment by MahyarFardin** [comment]
> Ultimately this is not going to be an extension issue.
> 
> Basically it's saying that your username/password that you are supposed to use when setting up the connection is incorrect.
> 
> Either that or your postgres server isn't configured properly to accept username/password over TCP - which is usually setup in the `pg_hba.conf` file.

Hello Mr.Chris,
Thank you for your guidance, my problem solved and you were right. I really appreciate your perfect extension and wish you the bests in developing that. 
regards
