### ISSUE TITLE
Can't add a new connection.

### ISSUE THREAD

**Issue by JeffPamplona** [Borvik/vscode-postgres#24]
Once filled the data Hostname, user, pass, port, and SSL an error message displays "Cannot read property 'context' of null". Additionally, when I click on the bottom bar on Select Postgres Server, it thorws "Cannot read property 'globalState' of null". It seems to happen on every command, except "New Query".

**Comment by Borvik** [comment]
While the error messages are different, the cause is the same error as another issue, so I will be marking this as a duplicate.

Duplicate of #19

**Comment by Borvik** [comment]
Duplicate of #19
