### ISSUE TITLE
How to edit a database configuration?

### ISSUE THREAD

**Issue by haisamido** [Borvik/vscode-postgres#26]
I created a database configuration but how do I edit that configuration?

**Comment by Borvik** [comment]
Currently there is no way to edit a connection (as that is really the only configuration that needs to be done).

The only way around is to delete and re-add.

**Comment by Borvik** [comment]
maybe a way to edit a configuration would be to implement a virtual file system via the FileSystem API: https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample.

Only a subset of it would need to be implemented with the rest returning fake data, opening/saving would be the crucial ones.

**Comment by Borvik** [comment]
This should be available in the next release.
