### ISSUE TITLE
Configuration Issue(s)

### ISSUE THREAD

**Issue by lincoln017** [Borvik/vscode-postgres#28]
Installed the plugin for VS Code on MacOSX.  Added the postgreSQL connection successfully, and see my database in the explorer.  Have also confirmed that when typing SQL that intellisense correctly completes tables and fields names.  However, I'm simply unable to execute any queries against the database.  

When I run the query (F5 or right-mouse-menu to Run the Query) it brings up another window to the right with two tabs -- my .sql file duplicated and a Results which reads:

    Results not found: postgres-results://file:///my/file/dummy.sql

Further, if I attempt to run any queries from the Explorer (select top 1000, for example), I get the same behavior - a mother pane to the right with two tabs - the SQL and the results tab (which instead reads "Results not found: postgres-results://untitled:untitled-1"

Clearly I'm missing something in the config / setup but just can't figure it out.

Thanks in advance.

**Comment by Borvik** [comment]
I don't think you're missing any config/setup - I wanted it to be simple, and if you are able see the database and pull table/field names something else must be going on.

Unfortunately I do not have a Mac to be able to test on one.

There might be some more data to find regarding the specific issue in the Output window, you might have to select PostgreSQL from the dropdown.

I wonder if this is related to the same issue plaguing Windows users - strangely though Linux has been unaffected.

![image](https://user-images.githubusercontent.com/1764750/42392702-b0ba338e-8121-11e8-92c4-8be9777ae5ab.png)

**Comment by lincoln017** [comment]
Strange - the Output window shows simply summary data -- ie, "33 rows selected" for a SQL statement that is simply "select * from tablename" where indeed the table has 33 rows.  But I can't find the actual data displayed anywhere.

Not sure how the execution output is captured and piped back to the VSCode GUI, but am unable to see anything suspicious in log files.  

Do you know if anyone is successfully using this extension on MacOSX?  Is there anything else I can look at or tweak to help figure it out?

**Comment by yanok1** [comment]
This issue started to present to me since last vscode update (described below) on Linux Mint 18.3 Cinnamon 64 bits as well:

> Version: 1.25.0
> Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
> Date: 2018-07-05T13:10:37.273Z

**Comment by Borvik** [comment]
I can now confirm this on Windows as well - seems there may be an api change in version 1.25.

**Comment by Borvik** [comment]
this should be fixed in 1.0.11
