### ISSUE TITLE
Add DB Views to the explorer

### ISSUE THREAD

**Issue by Borvik** [Borvik/vscode-postgres#3]
Could also then add to intellisense.

Icons to use?
Mixed with tables or separate?
Intellisense icons are based on the CompletionKind - and are separate from icons in the explorer

**Comment by GammaGames** [comment]
We currently use adminer, it lists all views and tables in one list. It makes the view text slightly different depending on the theme, but using an eye icon and making the text italic would probably be enough to differentiate between tables and views.

**Comment by Borvik** [comment]
Implemented in version 1.0.2
