### ISSUE TITLE
Results not found: postgres-results://untitled:untitled-1

### ISSUE THREAD

**Issue by GammaGames** [Borvik/vscode-postgres#31]
Using a simple query:

```sql
select *
from table
limit 10
```

It prints `Results not found: postgres-results://untitled:untitled-1` in the results tab, and opens the pgsql file next to the results. The same happens when I save the file and run the query.

In the output for the extension it prints out `10 rows selected` every time I run the query. So it must be working, partially!

**Comment by Borvik** [comment]
Duplicate issue #28 - also fixed in 1.0.11

**Comment by GammaGames** [comment]
Awesome, thank you! Works great :)
