### ISSUE TITLE
Problem Connecting to Remote Database

### ISSUE THREAD

**Issue by lincoln017** [Borvik/vscode-postgres#32]
Running Visual Studio Code with the Postgres extension on the same machine works fine.  When I run VSCode with the extension from a different client machine on the same network, I get the following error:

   no pg_hba.conf entry for host "XX.XX.XX.XX", user "NNN", database "NNN", SSL off

But there *IS* a valid entry in the pg_hba.conf file, and I've confirmed it is valid by virtue of using a different tool (JetBrains DataGrip) to access the database from the aforementioned client machine.

Any suggestions?

**Comment by Borvik** [comment]
The database server is most likely returning that error, not the extension, or the client library the extension uses (https://www.npmjs.com/package/pg).  I would at least start with verifying the connection details.

Does the DB explorer work?

**Comment by lincoln017** [comment]
The DB explorer does not work.  Note - I do NOT have PostgreSQL installed on the client machine.  Could I therefore be missing certain libraries that were otherwise present when running VSCode and PostgreSQL on the same machine?  

I did an NPM install of the pg package you referenced above, but not sure how to test / run this to further diagnose the issue.

**Comment by Borvik** [comment]
you shouldn't need to run npm install - that is just a library used by the extension.

the pg_hba.conf - does the user you are using have limited database access?  is it "all"?

the extension uses the "postgres" database to query the structure of the database.

**Comment by lincoln017** [comment]
I've tried multiple variations of the pg_hba.conf file -- my specific database/user, all / all, postgres / all, etc. -- and get the same error each time.

**Comment by Borvik** [comment]
ok, so I just installed a remote postgres server, setup my listen_address and my hba.conf - i was able to connect without errors (once I fixed my listen_address).

https://www.postgresql.org/docs/9.1/static/auth-pg-hba-conf.html

>  There is no "fall-through" or "backup": if one record is chosen and the authentication fails, subsequent records are not considered. If no record matches, access is denied.

I have seen that the record order in the pg_hba.conf file is important - perhaps that is what is going on.

**Comment by lincoln017** [comment]
I moved the entry to the top of the pg_hba.conf file but still got the same error.  I'm not sure what you mean when you say you fixed your listen_address.  I simply used the IP address of my client machine to the pg_hba.conf file and ensured that the postgres config was reloaded after I updated it.

**Comment by Borvik** [comment]
A fresh install of postgres server defaults to only listen to localhost.  I had to edit my postgresql.conf file to listen on all network interfaces.  Probably not your issue if another pg client connected from the same machine.

The only other thing I can suggest is try removing the connection from the DB explorer, and readding it.  Perhaps something in the connection details is not the same.

**Comment by Borvik** [comment]
As I have successfully tested a remote connection, and the error message is being generated by the server - this isn't really an issue with the extension and will be closed.
