### ISSUE TITLE
error: unrecognized privilege type: "TEMP, CONNECT"

### ISSUE THREAD

**Issue by AlexFiliakov** [Borvik/vscode-postgres#34]
Hi, I added my database following the prompts (label, host, username, password, port, SSL left blank). The database entry gets added to the Postgresql Explorer sidebar, but when I expand this db it only shows the error message:
**error: unrecognized privilege type: "TEMP, CONNECT"**
instead of listing the db details.

If I try to run a query (F5) it throws a popup error on lower right "**database <username> does not exist**" where <username> is my username I entered when adding the connection.

This looks like it's trying to use the username in place of the database name, so perhaps it's mapping the config entries to wrong fields.

**Comment by Borvik** [comment]
When you expand the connection, the extension queries the server for all the databases you are allowed access to.  In this case, it is using ```has_database_privilege(datname, 'TEMP, CONNECT')```.

My best guess is you are using a PostgreSQL version prior to 8.2 which is where the CONNECT permission was introduced.

**Comment by Borvik** [comment]
Since the oldest version of PostgreSQL that is still supported is 9.3, I will be closing this.

**Comment by AlexFiliakov** [comment]
That's unfortunate. I think the latest version of our DB is based on PostgreSQL 8.3: https://en.wikipedia.org/wiki/Greenplum
