### ISSUE TITLE
When having entered all conn details, error notification message: "The name org.freedesktop.secrets was not provided by any .service files"

### ISSUE THREAD

**Issue by metaleap** [Borvik/vscode-postgres#38]
Any ideas what's missing at my end? Some package? Would a VSCode/NodeJS pkg really rely directly on something from freedesktop? I'm on Void Linux, i3, half of LXDE present on the system.

This comes up routinely after having entered all prompts in the series of inputboxes following a click on 'Add Connection'. New connection also doesn't show up in your 'PostgreSQL Explorer' view. The conn details are correct and the conn can be successfully established when trying via _LibreOffice Base_ connection wizard. (_Base_ doesn't work at my end though, past its initial conn wizard.)

**Comment by metaleap** [comment]
libsecret is installed and up to date. When searching for the message, I see a lot of "gnome-keyring" and "NetworkManager" notices, neither of which I'm using or intending to. Ah well --- feel free to close if you wish as this seems if anything an issue with keytar or other 3rd-party dep

**Comment by Borvik** [comment]
Yeah, didn't really want to store the passwords in plain text and keytar was what several other extensions were using - and was recommended for storing passwords.  I don't plan on changing that - sorry it didn't work for you.
