### ISSUE TITLE
Using SSL connection

### ISSUE THREAD

**Issue by hoanghapham** [Borvik/vscode-postgres#40]
My company's database requires a SSL connection. Is it possible to do so with this extension?

**Comment by Borvik** [comment]
Yes/no - that's in a weird state right now.

Currently as long as you specify a certificate file (which could be ANY file really), it enables SSL mode.

There are plans to make this easier/more clear - see #39

**Comment by hoanghapham** [comment]
Thanks! Looking forward to it.
