### ISSUE TITLE
Problem with results when doing Left, right or outer joins

### ISSUE THREAD

**Issue by daguito81** [Borvik/vscode-postgres#43]
So I was recreating the example here (https://blog.codinghorror.com/a-visual-explanation-of-sql-joins/) of different joins using VSC and this extension.
Whenever I do SELECT * FROM table_a  and the same for table_b I get the correct results.
![image](https://user-images.githubusercontent.com/14969458/44153768-65db957c-a0a9-11e8-813a-4e02718ad38a.png)

When I do an INNER JOIN I also get the result that I'm expecting which is a match from both tables
![image](https://user-images.githubusercontent.com/14969458/44153836-8ac9ccb4-a0a9-11e8-9d05-2a4ebcf11303.png)

But then, when I do a full outer join I get this:

![image](https://user-images.githubusercontent.com/14969458/44154008-ed675c56-a0a9-11e8-862a-37970f5eee6c.png)

Which has several problems. 1) The id in pirate on the left should be 1 2) you have rows where both are being shown as null and then the last 2 rows have a match when those should be only on table_ b
Running the same query on the same server using DataGrip gives out: 
![image](https://user-images.githubusercontent.com/14969458/44154080-258c802a-a0aa-11e8-9796-edac28e5e608.png)

Which is the right answer according to the website. 

LEFT JOIN gives out  this:
![image](https://user-images.githubusercontent.com/14969458/44154124-472a059a-a0aa-11e8-8dfb-ca8da975be9e.png)

Where it should be:
![image](https://user-images.githubusercontent.com/14969458/44154143-53a8d8f0-a0aa-11e8-9328-16ed2ded67e5.png)

Again using the same database and same query on DataGrip

Doing a RIGHT JOIN gives:
![image](https://user-images.githubusercontent.com/14969458/44154212-7ea147ea-a0aa-11e8-8c06-c17c1fd94d4a.png)

When again using DataGrip we get the right answer: 
![image](https://user-images.githubusercontent.com/14969458/44154235-8cd9cfda-a0aa-11e8-88b7-765189ae6c51.png)

I originally thought it was a problem with my database but considering other software is giving out the result as is using the same exact queries and database I'm wondering what could be causing these kind of problems?

**Comment by Borvik** [comment]
This could be tricky - not finding the issue, but solving it.  I can already tell you the cause of the issue.  Javascript.  The results are coming back as a named object, where the column names are the properties.  An object can only have one instances of any given property, and the query results show four columns.

I'll have to do some digging on how the query results are returned to figure out the next steps.

**Comment by daguito81** [comment]
Just to give you confirmation. I tried it out with the new version and it worked fine. Thank you for the help

![image](https://user-images.githubusercontent.com/14969458/44205143-a8bc3980-a155-11e8-94a5-fb371dc8deeb.png)
