### ISSUE TITLE
Show foreign key icon

### ISSUE THREAD

**Issue by kyle-john** [Borvik/vscode-postgres#44]
![image](https://user-images.githubusercontent.com/16515307/44243950-83d6cd80-a20c-11e8-9fa1-8bb6dbcf312f.png)

`dics_id` is a foreign key, but its icon is the same with other columns. It confused me.

**Comment by Borvik** [comment]
I'm sorry it confused used.  During initial planning I did look into this, but put it off until I could find a solution.  There are two challenges to this.

1. Identifying columns that are foreign keys in a nice succinct way for the column selection query.
2. Finding any icon for the color scheme of the icons used - as a key already indicates Primary Keys, and we want to avoid confusion there as well.

I might have an idea about the first one, but we'll see.

**Comment by Borvik** [comment]
Good news - I managed to find a solution for this.  It should be out in the next version sometime this weekend.
