### ISSUE TITLE
Result column types have weird names

### ISSUE THREAD

**Issue by lnicola** [Borvik/vscode-postgres#45]
E.g. `int4` for integer and `_text` for `text[]`.

**Comment by Borvik** [comment]
I'm actually using postgres' own data for the display of column names.

While `int4` might be a little odd, I am more worried about the `_text` for an array field - that one would definitely be nice to clean up.  I have to play around with this.

**Comment by lnicola** [comment]
I can't quickly find the definition of `FieldInfo` from [here](https://node-postgres.com/api/result#-code-result-fields-array-lt-fieldinfo-gt-code-), mmaybe it has a `modifier` of sorts?

**Comment by lnicola** [comment]
```sql
select oid, format_type(oid, typtypmod)
from pg_type
```

**Comment by Borvik** [comment]
Thanks for the pull request, I'll probably merge that sometime this weekend.  I was using that function for the db explorer, but obviously not in the general queries.

Also, that spot you thought might be a tad slow, that isn't iterating on each row - that's iterating the fields - for possibly multiple queries.

**Comment by lnicola** [comment]
> Also, that spot you thought might be a tad slow, that isn't iterating on each row - that's iterating the fields - for possibly multiple queries.

Right, sorry, I missed that. Well, it might still be worth making an array with the `oid`s for indices (like a dictionary), although that's not clear-cut in C, and guessing about JS performance seems much harder :smile:.
