### ISSUE TITLE
Some syntax not supported

### ISSUE THREAD

**Issue by lnicola** [Borvik/vscode-postgres#48]
Possibly fixed by https://github.com/Borvik/vscode-postgres/projects/2.

```sql
begin;
select 1;
commit;
```

shows syntax errors for `begin` and `commit`.

PS: Your extension is awesome! I like the autocompletion, parameter and return type suggestions, and also being able to see multiple result sets at once.

**Comment by Borvik** [comment]
Yeah, it probably would be fixed by that - the challenge is in finding/building a language parser, and then building the language for it.  It is rather slow going on that front.

**Comment by StenliH** [comment]
CREATE TYPE processing_state AS **ENUM** ('loaded', 'all processed', 'error');

Here ENUM shows syntax error. Otherwise excellent work, man!

**Comment by govindrai** [comment]
The following valid sql statements show syntax errors:
![image](https://user-images.githubusercontent.com/13859249/90080797-6e43f380-dcc0-11ea-8ca5-3388767ef12e.png)
![Uploading image.png…]()

**Comment by bfelbo** [comment]
I'm seeing these syntax errors as well.

@Borvik any idea why this might be? Makes the SQL validation a bit useless if it fails on trivial cases like this.

**Comment by Borvik** [comment]
Currently the error validation is powered by postgres itself by prepending each statement with an `EXPLAIN` and running that.  Postgres itself is returning these errors.

`EXPLAIN` was not meant for `CREATE`/`ALTER` statements - but works good for `SELECT` statements.

However creating a whole parser that can do this analysis is tricky at best, but to also create one that can be kept up-to-date with the version of postgres anyone might be connected to... yeah... really not my forte (also this is a side-project I don't really have a lot of time to work on)
