### ISSUE TITLE
Add support for PostgreSQL 9.3

### ISSUE THREAD

**Issue by RafalSkorka** [Borvik/vscode-postgres#55]
Please add support for PostgreSQL 9.3.
The only thing that does not work with 9.3 is that it doesn't show table columns showing:

`error: function json_build_object(....) does not exist`

I was able to fix it by replacing 
```
ELSE json_build_object(
  'constraint', fk.constraint_name,
  'catalog', fk.fk_catalog,
  'schema', fk.fk_schema,
  'table', fk.fk_table,
  'column', fk.fk_column
) 
```
with

```          
ELSE row_to_json(
  SELECT d FROM (
    SELECT 
      fk.constraint_name as constraint,
      fk.fk_catalog as catalog,
      fk.fk_schema as schema,
      fk.fk_table as table,
      fk.fk_column as column
  ) d
)
```

in the tableNode.js file.
Seems like a small change and this excellent extension would work with PostgreSQL 9.3

**Comment by Borvik** [comment]
a reasonable change - I hope to work on it this weekend
