### ISSUE TITLE
Extension is forcing me to enter a password

### ISSUE THREAD

**Issue by leye0** [Borvik/vscode-postgres#59]
If I use null, if I remove the "password" entry from the json, or if I put an empty string, I get:

password: "": Failed to save 'f3b63ee0-c748-11e8-ab74-631ef94fbdbf.json': Password is required.
password: null: Failed to save 'f3b63ee0-c748-11e8-ab74-631ef94fbdbf.json': Password is required.
(removing the line): Failed to save 'f3b63ee0-c748-11e8-ab74-631ef94fbdbf.json': Missing "password" key

What do I do?

**Comment by Borvik** [comment]
Looks like this is an issue with Keytar not accepting an empty or null password.

This is something being worked on. A solution was _ALMOST_ had with #57, but I found that would break existing connections.

I've got an idea on a solution - we shall see this weekend when I get some time to address it.

**Comment by leye0** [comment]
By the way, I saw that I was using the wrong port, and when targetting the proper port, PSQL was accepting any password for this connection, so this is not a blocker and the workaround is to have the password key present and the password value filled with anything.

**Comment by leye0** [comment]
Oh, sorry, I just read the other issue. We should reference the other and close this one.

**Comment by Borvik** [comment]
This should be fixed in version 1.1.3
