### ISSUE TITLE
Connection aware code completion not working

### ISSUE THREAD

**Issue by jonsel087** [Borvik/vscode-postgres#61]
Hi,
I was able to connect to my postgres instance (PostgreSQL 9.4.7 on x86_64). I created a new .pgsql files, specified the connection and database. I'm able to explore the db in the navigator, however there is no auto-completion for tables/columns. 
Is this feature fully supported? Anything else i should check?

"Output" Terminal Reads this error when attempting code completion:
```
[Error - 11:17:23 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'attname' of null
  Code: -32603 
```

**Comment by Borvik** [comment]
It should support auto-completion for tables/columns - it looks like there is some kind of error attempting to _get_ the names.

The difficulty is from that error message I can't tell if it's from the main extension or the language server - or if the error is coming directly from a query or from the code processing the query results.

Sometimes I have noticed that auto-completion fails (never checked the output at those times), and switching window contexts, and then back to the query fixes the connection and allows it to work again.

**Comment by jonsel087** [comment]
hi @Borvik ,

> The difficulty is from that error message I can't tell if it's from the main extension or the language server - or if the error is coming directly from a query or from the code processing the query results.

Can you advise on any way to dig into this? happy to post results. I have tried switching windows and creating new workspaces, etc. Nothing seems to affect it. 

Also, can you confirm if it's better to use the 'pgsql' file type or 'Postgres'? I think i mainly get the debug error when i use 'Postgres'

**Comment by Borvik** [comment]
What about your status bar?  What does it look like?
![image](https://user-images.githubusercontent.com/1764750/47602685-3fa43e00-d9b0-11e8-901a-47decde53f64.png)

**Comment by jonsel087** [comment]
Hi,

The status bar shows a good connection to the server/database.
I just updated to the latest version, and after a few tries was finally
able to get the schema code completion working (FYI, it's very finicky
about the order in which you connect to a database, choose a language, and
save file. Saving the file will revert the language type from 'Postgres' to
'pgsql'. I've tried disabling and/or re-enabling the pgsql ext in case its
conflicting.

Frustratingly, now that the schema code completion is working, the language
completion isn't!

**Comment by jeaneric** [comment]
In my case, the error:

> [Error - 11:17:23 AM] Request textDocument/completion failed.
>   Message: Request textDocument/completion failed with message: Cannot read property 'attname' of null
>   Code: -32603

was cause by a table with no fields... an error. After deleting the table, the automcompletion works great.
