### ISSUE TITLE
Excuse me, did this extension support ssh channel connect mode?

### ISSUE THREAD

**Issue by andares** [Borvik/vscode-postgres#74]
I can not direct connect my pg server.

**Comment by Borvik** [comment]
If by ssh channel you mean an ssh tunnel.  As long as the tunnel is setup prior to connecting, I don't see why you couldn't point the port to the forwarded port.

**Comment by andares** [comment]
yes, it's ssh tunnel 😂 

I use pgsql by cloud service provider, so direct connect to database is not safe I see.

**Comment by Borvik** [comment]
Ok, then yes in theory there should be nothing stopping it from working.  There is nothing specifically in any of the code (extension or the pg library used for the actual connection) to has anything to do with the tunnel - as that is all handled externally by ssh.  As long as you point the server to the machine establishing the tunnel (most commonly localhost) and the local port that is forwarded off to the server then it should work.

**Comment by andares** [comment]
That's ok, I understand. Thanks for your reply.
