### ISSUE TITLE
Losing syntax highlighting if first character of query is a blank space

### ISSUE THREAD

**Issue by NathaTerrien** [Borvik/vscode-postgres#79]
If, for layout purpose, the first character of query is one or more blank spaces, the syntax highlighting stops.

**Comment by Borvik** [comment]
This isn't simple.  The syntax highlighting is driven purely by the .tmLanguage file - I'm not certain where I found it, only that it mostly works.  I have noticed this same issue.

If anyone knows how to update that or of a better one - I would be open to ideas.
