### ISSUE TITLE
Can't run SQL queries.

### ISSUE THREAD

**Issue by vineelyalamarthy** [Borvik/vscode-postgres#80]
I installed this in VS code and when I try to run SQL queries, it can't run and fail with error like this.

![screen shot 2019-01-13 at 2 23 19 am](https://user-images.githubusercontent.com/515877/51084322-47849c00-16dc-11e9-9ce4-df3692537003.png)

**Comment by vineelyalamarthy** [comment]
Thank you so much. F5 worked well. Isn't clicking on the Run button more intuitive ? Thats how pgAdmin works as well.

**Comment by Borvik** [comment]
Problem is first, that button is provided by another extension - so not really able to trigger running the query from _that_ run button.  Then there is the built-in run button in the Debug panel - that really only works with the Launch configuration file (.vscode/launch.json).  A run button could possibly be created, but then anyone with the Code Runner extension installed would have **two** run buttons on their files - leading to confusion on which to press.

You're right, that _is_ how pgAdmin does it - but pgAdmin doesn't have to deal with the features of an IDE either.

**Comment by Borvik** [comment]
Closing the issue as it is not being generated by this extension.
