### ISSUE TITLE
Use libsecret instead of gnome-keyring

### ISSUE THREAD

**Issue by Sandarr95** [Borvik/vscode-postgres#82]
As discussed in #38, resolving this issue depends on the implementation of `keytar`. It seems that they addressed this issue as of `4.0.2`: https://github.com/atom/node-keytar/pull/53

Can this change be made? I'd like to implement/test but it's the first time I would be working on a vscode plugin so some pointers to start would really help me.

**Comment by Borvik** [comment]
Actually that is not a change I can make.  I _am_ using keytar - but it is a core module from vscode that I am using.  VS Code actually would need to update the version of keytar they include.

**Comment by Borvik** [comment]
Also that looks like it was merged in Apr. 2017 for version 4.0.2.
Their latest version is 4.3 (https://github.com/atom/node-keytar/blob/master/package.json) and the version included with vscode is 4.2 (https://github.com/Microsoft/vscode/blob/master/package.json).
