### ISSUE TITLE
Perform authentication using externalbrowser

### ISSUE THREAD

**Issue by japborst** [Borvik/vscode-postgres#83]
When using single sign-on like Google, authentication is done through the browser. Setting the ODBC authenticator to `externalbrowser` solves this issue.

Is it possible to achieve this using this plugin? This one is most complete and I haven't found another that does support it.

Thanks.

**Comment by Borvik** [comment]
Ok, trying to wrap my head around how ODBC single sign-on with a browser based provider would even work...  yea... If you've got some documentation you can point me at I can look at it.
