### ISSUE TITLE
Not seeing PostgresSQL in the Explore pane 

### ISSUE THREAD

**Issue by sjmcdowall** [Borvik/vscode-postgres#88]
I just installed this -- and although I do see the little Icon in the left most pane thing -- I am not seeing the PostgresSQL in the Explorer window as seen in the documentation.  See screenshot .. I did restart VS Code just in case.

This is on a Mac OS X -- latest VS Code .. latest plugin (one presumes) 

<img width="2128" alt="screen shot 2019-03-01 at 8 17 52 am" src="https://user-images.githubusercontent.com/2034925/53640601-88882f80-3bfa-11e9-82e8-4cdb94fca015.png">

**Comment by Borvik** [comment]
The explorer has moved.  Earlier versions of vscode didn't allow plugins to have their own sidebar.  As soon as it was available, the db explorer moved to its own sidebar - available by clicking the icon you mentioned.

**Comment by sjmcdowall** [comment]
Well -- I would suggest than that the documentation be updated to reflect that?  It pretty clearly shows the "old" style Explorer stuff which is pretty confusing to new people ...
