### ISSUE TITLE
ERROR:  column p.proisagg does not exist at character 254 on Postgres 11

### ISSUE THREAD

**Issue by samlee1203** [Borvik/vscode-postgres#92]
I saw #72 issue had been reported and fixed/closed.
I am still seeing the same issue(or different) whenever I run the "select top 1000" query.

plugin version: 1.1.7

error message from VS Code output panel :
"column p.proisagg does not exist"

from postgre log(on the server) : 

2019-03-07 18:27:13.910 KST [11181] ERROR:  column p.proisagg does not exist at character 254
2019-03-07 18:27:13.910 KST [11181] HINT:  Perhaps you meant to reference the column "p.prolang".
2019-03-07 18:27:13.910 KST [11181] STATEMENT:  
	      SELECT n.nspname as "schema",
	        p.proname as "name",
	        d.description,
	        pg_catalog.pg_get_function_result(p.oid) as "result_type",
	        pg_catalog.pg_get_function_arguments(p.oid) as "argument_types",
	      CASE
	        WHEN p.proisagg THEN 'agg'
	        WHEN p.proiswindow THEN 'window'
	        WHEN p.prorettype = 'pg_catalog.trigger'::pg_catalog.regtype THEN 'trigger'
	        ELSE 'normal'
	      END as "type"
	      FROM pg_catalog.pg_proc p
	          LEFT JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
	          LEFT JOIN pg_catalog.pg_description d ON p.oid = d.objoid
	      WHERE
	        pg_catalog.pg_function_is_visible(p.oid)
	        AND p.prorettype <> 'pg_catalog.trigger'::pg_catalog.regtype
	            AND n.nspname <> 'information_schema'
	        AND has_schema_privilege(quote_ident(n.nspname), 'CREATE, USAGE') = true
	        AND has_function_privilege(p.oid, 'execute') = true
	      ORDER BY 1, 2, 4;
	      
I am still able to perform the select query with no issue, but this error message is keep showing whenever I do the queries. This is increasing the server log as well of course. 

Thanks,
Sam

**Comment by Borvik** [comment]
Looks like the language server got missed when when other area got fixed.

I have a potential fix in the works, but no PG11 to test against yet.  Working on that to make sure its ready.

**Comment by Borvik** [comment]
This should be available in 1.1.8
