### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by thekingf4** [Borvik/vscode-postgres#99]
- Issue Type: `Performance`
- Extension Name: `vscode-postgres`
- Extension Version: `1.1.10`
- OS Version: `Linux x64 4.18.0-17-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/luis/ckolkman.vscode-postgres-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Borvik** [comment]
I am not seeing an attached file for analysis.  Also would be good to confirm what was going on when this was generated.
